### PR TITLE
Implemented tests to ToolMakerHutFields and fixed bugs there

### PR DESCRIPTION
**Pull request by scythehazker**

### CODE REVIEW

**Comment by p3peka** [comment]
Tests cover the class, bugs are removed. Approved

**Review by p3peka — COMMENTED** [review]
Tests cover the class, bugs are removed. Approved

**Review by p3peka — CHANGES_REQUESTED** [review]
I recommend resubmitting the code again to make sure that the current changes to main have not broken the functionality.

**Review by quendingoldo — APPROVED** [review]
New changes really helped and I think they fixed problems with merging. I appreciate detailed tests.

Disabling duplicate-code is not, as we all know, best option, but, honestly, the original design does not help with making these adaptors less duplicated at all. We could add new class as something like template for three adaptors, but it would be way less readable.

Also calling `new_turn` methods for removing players from locations is not the best option, rewriting of `new_turn` can be considered.

But these problems are not so significant. I hope it will merge and work correctly now.

**Review by p3peka — APPROVED** [review]

**Pull request merged**
